config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  get 'accounts/login', to: 'accounts#login'
  get 'accounts/register', to: 'accounts#register'

  resources :listings, only: [:show]
  resources :products, only: [:show] do
    get 'search', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def register
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/accounts/register.html.erb
<h1>Accounts#register</h1>
<p>Find me in app/views/accounts/register.html.erb</p>

app/views/home/index.html.erb
<div class="row gutter-10">
  <div class="col-xs-12 col-md-3">
    <ul class="card main-category list-unstyled hidden-xs" style="background-color:white;">
      <li>
        <span><a href="#">Women’s Clothing</a></span>
      </li>
      <li>
        <span><a href="#">Men’s Clothing</a></span>
      </li>
      <li>
        <span><a href="#">Phones &amp; Accessories</a></span>
      </li>
      <li>
        <span><a href="#">Computer &amp; Office</a></span>
      </li>
      <li>
        <span><a href="#">Consumer Electronics</a></span>
      </li>
      <li>
        <span><a href="#">Jewelry &amp; Watches</a></span>
      </li>
      <li>
        <span><a href="#">Home &amp; Garden, Furniture</a></span>
      </li>
      <li>
        <span><a href="#">Bags &amp; Shoes</a></span>
      </li>
      <li>
        <span><a href="#">Toys, Kids &amp; Baby</a></span>
      </li>
      <li>
        <span><a href="#">Sports &amp; Outdoors</a></span>
      </li>
      <li>
        <span><a href="#">Health &amp; Beauty, Hair</a></span>
      </li>
      <li>
        <span><a href="#">Automobiles &amp; Motorcycles</a></span>
      </li>
      <li>
        <span><a href="#">Home Improvement</a></span>
      </li>
    </ul>
  </div>

  <div class="col-xs-12 col-md-9">
    <div class="row gutter-10">
      <div class="col-xs-12 col-md-9">
        <div class="row">
          <div class="col-xs-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                <div class="item active">
                  <img style="width:100%; height:343px;" src="https://uproxx.files.wordpress.com/2017/06/bexar-3.jpg?quality=100&w=650" alt="...">
                  <div class="carousel-caption">
                    test
                  </div>
                </div>
                <div class="item">
                  <img style="width:100%; height:343px;" src="https://uproxx.files.wordpress.com/2017/06/bexar-3.jpg?quality=100&w=650" alt="...">
                  <div class="carousel-caption">
                    test
                  </div>
                </div>
                <div class="item">
                  <img style="width:100%; height:343px;" src="https://uproxx.files.wordpress.com/2017/06/bexar-3.jpg?quality=100&w=650" alt="...">
                  <div class="carousel-caption">
                    test
                  </div>
                </div>
              </div>

              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>

        <div class="card" style="margin-top:10px;">
          <h4 class="card__header">
            <span>Hot Deal!</span>
          </h4>

          <div class="row gutter-10 slick">
            <% 10.times.each do %>
              <div>
                <div class="thumbnail" style="margin-bottom:10px">
                  <img src="http://www.signatureholidays.co.in/images/karnataka/coorg/paddington-resort/green-fields-around-paddington-resort-coorg.jpg" alt="...">
                  <div class="caption">
                    <h5>Thumbnail label</h5>
                    <strong style="color:red">$5.00</strong>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="card" style="margin-top:10px;">
          <h4 class="card__header">
            <span>Hot Hit!</span>
          </h4>

          <div class="row gutter-10">
            <% 3.times.each do %>
              <div class="col-xs-12 col-md-4">
                <div class="thumbnail" style="margin-bottom:10px">
                  <img src="http://www.signatureholidays.co.in/images/karnataka/coorg/paddington-resort/green-fields-around-paddington-resort-coorg.jpg" alt="...">
                  <div class="caption">
                    <h5>Thumbnail label</h5>
                    <strong style="color:red">$3.00</strong>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="card" style="margin-top:10px;">
          <div class="row">
            <div class="col-xs-12">
              <img class="img-responsive" src="http://www.forever21.com/images/en/20160704/promo-july-fourth.gif" alt="">
            </div>
          </div>
        </div>

        <div class="card" style="margin: 30px 0 -10px;">
          <h4 class="card__header">
            <span>Latest posts!</span>
          </h4>
        </div>

        <div class="row">
          <% 20.times.each do %>
            <%
              img_url = [
                          "http://mtviewmirror.com/wp-content/uploads/2015/11/forever-21-dresses-3.jpg",
                          "http://www.forever21.com/images/1_front_750/00213980-01.jpg",
                          "https://s3cdn-lookbooknu.netdna-ssl.com/files/looks/medium/2011/12/10/1775671_nalookbook.jpg?1323523166",
                          "http://s3cdn-lookbooknu.netdna-ssl.com/files/looks/large/2015/11/05/4735087_image.jpg?1446683602",
                          "https://i.ytimg.com/vi/ld6vZMPKL9k/maxresdefault.jpg"
                        ].sample
            %>

            <div class="col-xs-12">
              <div class="card" style="background-color: white;padding:5px;border-radius:3px;margin-bottom:10px;position:relative">

                <img class="img-responsive" src="<%= img_url %>" alt="">
                <h4 class="card__product-title">Lorem ipsum dolor sit amet... <strong class="pull-right" style="color:red;">$5.00</strong></h4>
              </div>
            </div>
          <% end %>
        </div>

      </div>

      <div class="col-xs-12 col-md-3">
        <div class="card" style="padding: 5px">
          <img class="img-responsive" style="height: 333px;" src="http://assets.rpgsite.net/images/images/000/000/088/boxart/211_eu_psp.jpg" alt="">
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="google" content="notranslate" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <title>Sellingx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>


    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body style="background-color:#e9ebee;padding-top:65px;">
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path, class: 'brand' do %>
            <%= image_tag "cart.png" %>
            <span>SellingX</span>
          <% end %>
        </div>
        <div id="navbar" class="collapse navbar-collapse text-center">
          <form class="navbar-form" style="display:inline-block;">
            <div class="input-group">
              <input type="text" class="form-control" id="input-search" placeholder="I'm looking for ..." aria-describedby="sizing-addon1">
              <span class="input-group-btn">
                <%= link_to "Go!", search_products_path, class: 'btn btn-default' %>
              </span>
            </div>
          </form>



          <ul class="nav navbar-nav navbar-right" style="margin-right:0">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li>
                <!-- Update link signup -->
                <%= link_to 'Join FREE!', "#", id: "join-free-btn", data: { toggle: 'modal', target: '#modalEle' } %>
                <!-- <%= link_to 'Join FREE!', new_user_registration_path, id: "join-free-btn" %> -->
              </li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <%= yield %>
    </div>
    <%= render "shared/modal_box" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/listings/show.html.erb
<div class="row gutter-10">
  <div class="col-xs-12 col-md-3">
    <div class="filter-category hidden-xs">
      <h1 class="header">
        <i class="ico-category"></i>
        REFINE BY CATEGORY
      </h1>
      <ul class="menu list-unstyled">
        <li><a href="#">All Results</a></li>
        <li><a href="#">Mobiles & Tablets (37)</a></li>
        <li><a href="#">Computers & Laptops (29)</a></li>
        <li><a href="#">TV, Audio / Video, Gaming & Wearables (78)</a></li>
        <li><a href="#">Cameras (31)</a></li>
        <li>...</li>
        <li><a href="#" class="show-more">See More</a></li>
      </ul>

      <div class="interesting visible-lg">
        <h1 class="header">
          <i class="ico-category"></i>
          INTERESTING POSTS
        </h1>

        <ul class="list-unstyled list">
          <% 9.times.each do %>
            <li style="margin-bottom: 3px;">
              <a href="#">
                <img class="media-object" src="http://via.placeholder.com/90x90" alt="...">
              </a>
            </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>

  <div class="col-xs-12 col-md-6">
    <section class="filter">
      <span>Sort By: </span>
      <div class="btn-group btn-group-sm" aria-label="...">
        <button type="button" class="btn btn-default">Best matches!</button>

        <div class="btn-group btn-group-sm" role="group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Orders
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">Dropdown link</a></li>
            <li><a href="#">Dropdown link</a></li>
          </ul>
        </div>
        <div class="btn-group btn-group-sm" role="group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Orders
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">Dropdown link</a></li>
            <li><a href="#">Dropdown link</a></li>
          </ul>
        </div>
        <div class="btn-group btn-group-sm" role="group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Orders
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="#">Dropdown link</a></li>
            <li><a href="#">Dropdown link</a></li>
          </ul>
        </div>
      </div>

      <div class="pull-right hidden-xs">
        <span>View by: </span>
        <button type="button" class="btn btn-default" aria-label="Left Align">
          <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default" aria-label="Left Align">
          <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
        </button>
      </div>
    </section>

    <% 5.times.each do %>
      <div class="card" style="margin-bottom: 5px;">
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="http://via.placeholder.com/40x40" alt="...">
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Media heading</h4>
            <p>7mn</p>
          </div>
        </div>
        <div class="card-description">
          <p>NEW ARRIVAL AVAILABLE IN STORE
            ✦WOMEN BOOMER JACKET (97083)
            ✦ Price : 25.50$
            ✦ Color : Same as picture
            ✦ Size : XS, S, M</p>
        </div>
        <div class="card-media">
          <img class="img-responsive img-thumbnail" src="https://s-media-cache-ak0.pinimg.com/736x/35/58/be/3558be7208ab4853aca2616f6909ea92--purple-hoodies-fall-clothes.jpg" alt="">
        </div>
      </div>
      <% end %>
  </div>

  <div class="col-xs-12 col-md-3">
    <div class="panel panel-default" style="margin-bottom: 5px;">
      <div class="panel-heading">Member Status</div>
      <div class="panel-body">
        <div class="media">
          <div class="media-left">
            <a href="#">
              <img class="media-object" src="http://www.proflowers.com/blog/wp-content/plugins/pf-flowertypes/image/flower-197343.jpg" style="width:48px" alt="...">
            </a>
          </div>

          <div class="media-body">
            <h4 class="media-heading">Media heading</h4>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
            <p style="font-size: 12px;color: #7d7d7d;font-style: italic;">Seller's Products: Best Prices In Singapore</p>
          </div>
        </div>

        <ul>
          <li>Online Status: Offline</li>
          <li>Member Type: Premium</li>
          <li>Registered Date: 26-Jul-2017</li>
          <li>Last Online: 30-Nov</li>
        </ul>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Contact information</div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <li>Phone: 098 234 222</li>
          <li>Email: sale@aaa.com</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_login.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'form-horizontal form'}) do |f| %>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
      <% end %>
      <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password' %>
    </div>
  </div>
  <% if devise_mapping.rememberable? -%>
    <div class="form-group">
      <div class="col-sm-2">&nbsp;</div>
      <div class="col-sm-10">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>
    </div>
  <% end -%>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Login", class: 'btn btn-default' %>
      <%= link_to 'Forget Password?', new_user_password_path, class: 'forget-password' %>
    </div>
  </div>
<% end %>

app/views/shared/_form_reg.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'form-horizontal form'}) do |f| %>
  <%= devise_error_messages! %>

  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.email_field :email, autofocus: true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
      <% end %>
      <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create new account", class: 'btn btn-default' %>
      <%= link_to 'Forget your password?', new_user_password_path %>
    </div>
    <div class="col-sm-offset-2 col-sm-10">
      <p>Already have an account? <%= link_to 'Log in', new_user_session_path %></p>
    </div>
  </div>
<% end %>

app/views/shared/_modal_box.html.erb
<div class="modal fade" id="modalEle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog modal-lg vertical-align-center" role="document">
      <div class="modal-content" style="min-height: 380px">
        <div class="modal-body">
          <div class="row">
              <div class="col-md-8">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#login" aria-controls="home" role="tab" data-toggle="tab">Login</a></li>
                  <li role="presentation"><a href="#register" aria-controls="profile" role="tab" data-toggle="tab">Register</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="login">
                    <%= render 'shared/form_login' %>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="register">
                    <%= render 'shared/form_reg' %>
                  </div>
                </div>

                <ol class="hidden">
                  <li>show login and register form as tab</li>
                  <li>login with facebook</li>
                  <li>forget password</li>
                </ol>
              </div>
              <div class="col-md-4">
                Advantage to be a membership
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SellingX</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="fa fa-lock"></i> Login</a></li>
        <li><a href="#"><i class="fa fa-user"></i> Sign up</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>